name: Firebase Web CI

on:
  push:
    branches:
      - main
      - staging

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Archive Production Artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@main
        with:
          name: build
          path: build
      - name: Archive Staging Artifact
        if: github.ref == 'refs/heads/staging'
        uses: actions/upload-artifact@staging
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Download Artifact Production
        uses: actions/download-artifact@main
        if: github.ref == 'refs/heads/main'
        with:
          name: build
          path: build
      - name: Download Artifact Staging
        uses: actions/download-artifact@staging
        if: github.ref == 'refs/heads/staging'
        with:
          name: build
          path: build
      - name: Deploy to Firebase Staging
        uses: w9jds/firebase-action@staging
        if: github.ref == 'refs/heads/staging'
        with:
          args: deploy --only hosting -P staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Deploy to Firebase Production
        uses: w9jds/firebase-action@main
        if: github.ref == 'refs/heads/main'
        with:
          args: deploy --only hosting -P production
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
