name: Build and Deploy Staging
on:
  push:
    branches:
      - staging
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
        env: 
          REACT_APP_API_KEY:${{ secrets.REACT_APP_API_KEY_DEV }} 
          REACT_APP_AUTH_DOMAIN:${{ secrets.REACT_APP_AUTH_DOMAIN_DEV }} 
          REACT_APP_PROJECT_ID:${{ secrets.REACT_APP_PROJECT_ID_DEV }}
          REACT_APP_STORAGE_BUCKET:${{ secrets.REACT_APP_STORAGE_BUCKET_DEV }}
          REACT_APP_MESSAGING_SENDER_ID:${{ secrets.REACT_APP_MESSAGING_SENDER_ID_DEV }}
          REACT_APP_APP_ID:${{ secrets.REACT_APP_APP_ID_DEV}}
          REACT_APP_MEASUREMENT_ID:${{ secrets.REACT_APP_MEASUREMENT_ID_DEV }}

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting -P staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
